version: '3.8'

services:
  frontend-landing:
    build:
      context: ./frontend/landing-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  frontend-vr:
    build:
      context: ./frontend/vr-app
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./frontend/vr-app:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=your-secret-key-here
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - ./backend:/app
      - ./data:/data